---
name: kunturapp
description: Aplicativo movil Kuntur
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.1.0
  characters: ^1.1.0
  cloud_firestore: ^1.0.7
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.1.2
  firebase_core: ^1.1.0
  flutter_svg: ^0.22.0
  flutter_swiper: ^1.1.6
  intro_slider: ^2.4.1
  json_annotation: ^4.0.1
  json_serializable: ^4.1.1
  provider: ^5.0.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  smooth_page_indicator: ^0.2.3
  webview_flutter: ^2.0.4
  app_settings: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/siluets/accipitridae_2020-09-06/
    - assets/siluets/alcedinidae_2020-10-29/
    - assets/siluets/anatidae_2020-10-29/
    - assets/siluets/aramidae_2020-10-29/
    - assets/siluets/ardeidae_2020-10-29/
    - assets/siluets/bucconidae_2020-10-29/
    - assets/siluets/capitonidae_2020-10-29/
    - assets/siluets/cathartidae_2020-10-29/
    - assets/siluets/cinclidae_2020-10-29/
    - assets/siluets/columbidae_2020-10-29/
    - assets/siluets/corvidae_2020-10-29/
    - assets/siluets/cotingidae_2020-10-29/
    - assets/siluets/cracidae_2020-10-29/
    - assets/siluets/cuculidae_2020-10-29/
    - assets/siluets/donacobidae_2020-10-29/
    - assets/siluets/emberizidae_2020-10-29/
    - assets/siluets/falconidae_2020-10-29/
    - assets/siluets/fregatidae_2020-10-29/
    - assets/siluets/fringilidae_2020-10-29/
    - assets/siluets/grallaridae_2020-10-29/
    - assets/siluets/icteridae_2020-10-29/
    - assets/siluets/jacanidae_2020-10-29/
    - assets/siluets/laridae_2020-10-29/
    - assets/siluets/mimidae_2020-10-29/
    - assets/siluets/momotidae_2020-10-29/
    - assets/siluets/parulidae_2020-10-29/
    - assets/siluets/picidae_2020-10-29/
    - assets/siluets/pipridae_2020-10-29/
    - assets/siluets/psittacidae_2020-10-29/
    - assets/siluets/rallidae_2020-10-29/
    - assets/siluets/ramphastidae_2020-10-29/
    - assets/siluets/recurvirostridae_2020-10-29/
    - assets/siluets/scolopacidae_2020-10-29/
    - assets/siluets/strigidae_2020-10-29/
    - assets/siluets/thraupidae_2020-10-29/
    - assets/siluets/threskiornithidae_2020-10-29/
    - assets/siluets/trochilidae_2020-10-29/
    - assets/siluets/troglodytidae_2020-10-29/
    - assets/siluets/trogonidae_2020-10-29/
    - assets/siluets/tyrannidae_2020-10-29/
    - assets/icons/
    - assets/images/
    - assets/onboard/
    - assets/familyIcons/
    - assets/typo/
    - assets/colors_uncheck/
    - assets/colors_active/
    - assets/icons/apple/centre.png
    - assets/icons/facebook/centre.png
    - assets/icons/google+/centre.png
    - assets/icons/twitter/centre.png

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/typo/ProximaNova-Regular.otf
          weight: 400
        - asset: assets/typo/Proxima-Nova-Regular-Italic.otf
          weight: 400
        - asset: assets/typo/Proxima-Nova-Semibold.otf
          weight: 600
    - family: GalanoGrotesque
      fonts:
        - asset: assets/typo/Galano Grotesque Bold.otf
          weight: 700
